[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "anda-day1"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"



[dependencies]
python = "3.13.*"
ipykernel = ">=7.3.0,<8"
pip = ">=26.1.2,<27"

[pypi-dependencies]
matplotlib = ">=3.10.9,<4"  # Actually should be <3.8, because of a viziphant bug that comes up at the end of the last tutorial.
numpy = ">=2.4.6,<3"
pandas = ">=3.0.3,<4"
scikit-learn = ">=1.9.0,<2"
seaborn = ">=0.13.2,<0.14"
neo = ">=0.14.4, <0.15"
nixio = ">=1.5.4, <2"
viziphant = ">=0.4.0, <0.5"
elephant = ">=1.2.0, <2"
pyocclient = ">=0.6, <0.7"

#### Jupyter Kernel

[tasks]
install-kernel = "python -m ipykernel install --user --name anda-d1"

### Jupyter Lab Environment (pixi run jupyter) #############

[feature.jupyter.dependencies]
python = "3.13.*"

[feature.jupyter.pypi-dependencies]
jupyterlab = ">=4"

[feature.jupyter.tasks]
jupyter = "jupyter lab"

[environments.jupyter]
features = ["jupyter"]
no-default-feature = true

################################################

